{
	// Place your snippets for makefile here. Each snippet is defined under a snippet name and has a prefix, body and 
	// description. The prefix is what is used to trigger the snippet and the body will be expanded and inserted. Possible variables are:
	// $1, $2 for tab stops, $0 for the final cursor position, and ${1:label}, ${2:another} for placeholders. Placeholders with the 
	// same ids are connected.
	// Example:
	// "Print to console": {
	// 	"prefix": "log",
	// 	"body": [
	// 		"console.log('$1');",
	// 		"$2"
	// 	],
	// 	"description": "Log output to console"
	// }

	"C++ Makefile": {
		"prefix": "cmake",
		"body": [
			"# By Thomas Truong",
			"# Quickly compiles and links every .cpp file in the",
			"# src folder, and places them into the bin folder.",
			"",
			"# Directory paths.",
			"SRC = ../src/",
			"BIN = ../bin/",
			"",
			"# Every object file needed for linking.",
			"OBJECTS = $1.o",
			"# The path of every object file.",
			"PATHS = $(foreach path, $(OBJECTS), $(BIN)$(path))",
			"",
			"# Function names to run.",
			"all: $1",
			"",
			"# Functions.",
			"$1: $(PATHS)",
			"  g++ -o $(BIN)$@ $^",
			"",
			"# Compile .cpp files to .o files.",
			"$(BIN)%.o: $(SRC)%.cpp",
			"  g++ -c -o $@ $<",
			"",
			"# make clean.",
			"clean:",
			"  rm -f $(BIN)*",
			""
		],
		"description": "Shortcut for a C++ Makefile."
	},
	"Java Makefile" : {
		"prefix" : "jmake",
		"body" : [
			"# By Thomas Truong",
			"# Quickly compiles every .java file in the src folder,",
			"# and places them into the bin folder.",
			"",
			"# All the functions to run.",
			"all: Files",
			"",
			"# Files function, uses all .java files in src.",
			"Files: $(wildcard ../src/*.java)",
			"\tjavac -d ../bin/ $^",
			"",
			"# Cleans up every class file in bin.",
			"clean:",
			"\trm -rf ../bin/*.class",
			""
		],
		"description": "Shortcut for a Java Makefile."
	}
}
